version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: weather-backend
    restart: always
    environment:
      - REDIS_URL=redis://weather-redis:6379
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    networks:
      - weather-net

  frontend:
    build:
      context: ./frontend
    container_name: weather-frontend
    restart: always
    networks:
      - weather-net

  redis:
    image: redis:7
    container_name: weather-redis
    restart: always
    networks:
      - weather-net

  nginx:
    image: nginx:alpine
    container_name: weather-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge
